import { Shield, Activity, FileText } from "lucide-react";
import PageTransition from "../components/PageTransition";

export default function About() {
  return (
    <PageTransition className="container max-w-3xl mx-auto px-4 py-8">
      <div className="text-center mb-16">
        <h1 className="text-4xl font-bold text-white mb-4">About Cardio.AI</h1>
        <p className="text-lg text-slate-400">Reliable, AI-powered cardiovascular health assessment.</p>
      </div>

      <div className="space-y-12">
        <Section
          icon={<Shield size={24} className="text-indigo-400" />}
          title="Our Mission"
          text="To democratize access to preliminary heart health insights using advanced machine learning, empowering individuals to take proactive control of their well-being."
        />

        <Section
          icon={<Activity size={24} className="text-indigo-400" />}
          title="How It Works"
          text="Our system analyzes key clinical vitals—such as blood pressure, BMI, and glucose levels—alongside lifestyle factors to compute a statistical probability of cardiovascular risk based on a dataset of over 70,000 patients."
        />

        <div className="p-6 bg-amber-500/10 border border-amber-500/20 rounded-2xl flex gap-4">
          <div className="shrink-0 pt-1">
            <FileText className="text-amber-400" size={24} />
          </div>
          <div>
            <h3 className="font-bold text-amber-200 mb-1">Medical Disclaimer</h3>
            <p className="text-amber-100/80 text-sm leading-relaxed">
              Cardio.AI is a statistical tool and <strong>not a medical device</strong>. It does not provide a diagnosis. The results generated by this system are for informational purposes only. Always consult a qualified healthcare professional for medical advice, diagnosis, and treatment.
            </p>
          </div>
        </div>
      </div>
    </PageTransition>
  );
}

function Section({ icon, title, text }) {
  return (
    <div className="flex gap-4 md:gap-6 group">
      <div className="shrink-0 w-12 h-12 rounded-xl bg-indigo-500/10 border border-indigo-500/20 flex items-center justify-center group-hover:scale-110 transition-transform">
        {icon}
      </div>
      <div>
        <h2 className="text-xl font-bold text-white mb-2">{title}</h2>
        <p className="text-slate-400 leading-relaxed">{text}</p>
      </div>
    </div>
  )
}